[mypy]
python_version = 3.8
warn_return_any = True
warn_unused_configs = True

[mypy-numpy]
ignore_missing_imports = True

[mypy-scipy]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-pandas]
ignore_missing_imports = True

[mypy-h5py]
ignore_missing_imports = True

[mypy-hdf5storage]
ignore_missing_imports = True

[mypy-nibabel]
ignore_missing_imports = True

[mypy-nibabel.*]
ignore_missing_imports = True

[mypy-nipy]
ignore_missing_imports = True

[mypy-nipy.*]
ignore_missing_imports = True

[mypy-torchvision.*]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-yaml]
ignore_missing_imports = True

[mypy-tqdm]
ignore_missing_imports = True

[mypy-seaborn]
ignore_missing_imports = True
