name: lint

on:
  push:
    branches: [ "lint" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint with ruff
        uses: chartboost/ruff-action@v1

  type-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        cache: "pip"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install mypy mypy-gh-action-report
        pip install .[all]

    - name: Static type check with mypy
      run: |
        mypy . | mypy-gh-action-report

